Votre demande a bien été enregistrée.<br/> Nous reviendrons vers vous dans les plus brefs délais	Your request has been sent<br/>We will be back to you soon
Pour toute demande d'estimation de votre bien, veuillez utiliser le formulaire ci-après. <br/>Merci	For any estimation, please fill the form below.<br/>Thank you
Pour tout contact, demande d'informations ou de rendez-vous veuillez utiliser le formulaire ci-après. <br/>Merci	For any request or to make an apointment, please fill the form below.<br/>Thank you

salutation	Salutation
language	Langue
lastname	Nom
firstname	Prénom
email	Email
tel	Téléphone
street	Rue
number	Numéro
zip	Zip
city	Ville
country	Pays
fax	Fax
ref	Reference du bien
refLink	Lien
comments	Message
itemCity	Localité du bien
