services:
      caravane_user.profile.form.type:
        class: Caravane\Bundle\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: caravane_user_profile }
      caravane_user.registration.form.type:
        class: Caravane\Bundle\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: caravane_user_registration }
