caravane_cms_node:
    resource: "@CaravaneCmsBundle/Resources/config/routing/node.yml"
    prefix:   /

caravane_cms_homepage:
    path:     /
    defaults: { _controller: CaravaneCmsBundle:Default:index }

caravane_cms_legal:
    path:     /legal
    defaults: { _controller: CaravaneCmsBundle:Default:legal }

caravane_cms_contact:
    path: /contact
    defaults: { _controller: CaravaneCrmBundle:Default:contact }

caravane_cms_page:
    defaults:  { _controller: CaravaneCmsBundle:Default:index }
    #pattern:   /cms/page/{id}
    pattern: /{uri}
    requirements:
      uri: ".+"
