imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @CaravaneUserBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'CaravaneCmsBundle:Form:fields.html.twig'



# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ CaravaneCmsBundle]
    #java: /usr/bin/java
    filters:
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~



# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            numeric_functions:
                geo: Caravane\Bundle\EstateBundle\AST\Functions\Geo
        mappings:
            StofDoctrineExtensionsBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Caravane\Bundle\UserBundle\Entity\User
    profile:
        form:
            type: caravane_user_profile
    registration:
        form:
            type: caravane_user_registration

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    format_listener:
       rules:
           - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
           - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }
    view:
        serialize_null: true
        view_response_listener: force

sensio_framework_extra:
    view:    { annotations: false }

braincrafted_bootstrap:
    less_filter: less

mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~


liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumbnail_medium:
            quality: 100
            filters:
                thumbnail: { size: [360, 180], mode: outbound,  allow_upscale: true }
                background: { size: [360, 180], color: '#fff' }
        thumbnail_medium_square:
            quality: 100
            filters:
                thumbnail: { size: [220, 220], mode: outbound, allow_upscale: true }
                background: { size: [220, 220], color: '#fff' }

        full_medium:
            quality: 100
            filters:
                thumbnail: { size: [1024, 1024], mode: inset, allow_upscale: true }
        full_large:
            quality: 100
            filters:
                thumbnail: { size: [1280, 1280], mode: inset, allow_upscale: true }
# api mobile
        thumbnail_api_square:
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: outbound, allow_upscale: true }
                background: { size: [300, 300], color: '#fff' }
        full_api:
            quality: 90
            filters:
                thumbnail: { size: [500, 300], mode: inset, allow_upscale: true }
                background: { size: [500, 300], color: '#fff' }
        home_api:
            quality: 90
            filters:
                thumbnail: { size: [500, 250], mode: inset, allow_upscale: true }
                background: { size: [500, 250], color: '#fff' }



        home_320:
            quality: 100
            filters:
                thumbnail: { size: [320, 171], mode: outbound, allow_upscale: true }
                background: { size: [320, 171], color: '#fff' }
        detail_320:
            quality: 100
            filters:
                thumbnail: { size: [320, 214], mode: outbound, allow_upscale: true }
                background: { size: [320, 214], color: '#fff' }
        thumbnail_320:
            quality: 100
            filters:
                thumbnail: { size: [160, 160], mode: outbound, allow_upscale: true }
                background: { size: [160, 160], color: '#fff' }


        home_375:
            quality: 100
            filters:
                thumbnail: { size: [375, 200], mode: outbound, allow_upscale: true }
                background: { size: [375, 200], color: '#fff' }
        detail_375:
            quality: 100
            filters:
                thumbnail: { size: [375, 250], mode: outbound, allow_upscale: true }
                background: { size: [375, 250], color: '#fff' }
        thumbnail_375:
            quality: 100
            filters:
                thumbnail: { size: [190, 190], mode: outbound, allow_upscale: true }
                background: { size: [190, 190], color: '#fff' }

        home_414:
            quality: 100
            filters:
                thumbnail: { size: [414, 220], mode: outbound, allow_upscale: true }
                background: { size: [414, 220], color: '#fff' }
        detail_414:
            quality: 100
            filters:
                thumbnail: { size: [414, 276], mode: outbound, allow_upscale: true }
                background: { size: [414, 276], color: '#fff' }
        thumbnail_414:
            quality: 100
            filters:
                thumbnail: { size: [207, 207], mode: outbound, allow_upscale: true }
                background: { size: [207, 207], color: '#fff' }


        home_768:
            quality: 100
            filters:
                thumbnail: { size: [768, 410], mode: outbound, allow_upscale: true }
                background: { size: [768, 410], color: '#fff' }
        detail_768:
            quality: 100
            filters:
                thumbnail: { size: [768, 512], mode: outbound, allow_upscale: true }
                background: { size: [768, 512], color: '#fff' }
        thumbnail_768:
            quality: 100
            filters:
                thumbnail: { size: [384, 384], mode: outbound, allow_upscale: true }
                background: { size: [384, 384], color: '#fff' }

        home_1024:
            quality: 100
            filters:
                thumbnail: { size: [1024, 547], mode: outbound, allow_upscale: true }
                background: { size: [1024, 547], color: '#fff' }
        detail_1024:
            quality: 100
            filters:
                thumbnail: { size: [1024, 683], mode: outbound, allow_upscale: true }
                background: { size: [1024, 683], color: '#fff' }
        thumbnail_1024:
            quality: 100
            filters:
                thumbnail: { size: [512, 512], mode: outbound, allow_upscale: true }
                background: { size: [512, 512], color: '#fff' }




jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src, %kernel.root_dir%/../app/Resources]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs, translations]
            extractors: [alias_of_the_extractor]


services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension


lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:      'caravane'                                      # ssh key pass phrase
    token_ttl:        604800


rms_push_notifications:
    ios:
        sandbox: false
        pem: %kernel.root_dir%/var/apns/apnsCert.pem # can be absolute or relative path (from app directory)
        passphrase: caravane8645



ivory_google_map:
    geocoder:
        # Enable the service
        enabled: true

        # Geocoder class
        class: "Ivory\GoogleMap\Services\Geocoding\Geocoder"
        provider:
            # Fake IP
            # If you set a fake IP, the parameter will replace the REMOTE_ADDR value by the given one
            #fake_ip: "123.345.567.123"

            # Provider class
            class: "Ivory\GoogleMap\Services\Geocoding\GeocoderProvider"

            # API key used by the provider
            # If you set an API key, this paremeter will be the second parameter provider constructor
            # By default, there is no api key ^_^
            #api_key: "apikey"

            # Locale used by the provider
            # If your set a locale, this parameter will be the second parameter provider constructor if there is no api key else it will be the third
            # By default, there is no locale
            locale: "en"

        # Adapter class
        adapter: "Geocoder\HttpAdapter\BuzzHttpAdapter"



knp_paginator:
    template:
        pagination: "KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig"
