caravane_crm:
    resource: "@CaravaneCrmBundle/Resources/config/routing.yml"
    prefix:   /



caravane_estate:
    resource: "@CaravaneEstateBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

caravane_cms:
    resource: "@CaravaneCmsBundle/Resources/config/routing.yml"
    prefix:   /

