MON COMPTE	MY ACCOUNT
Créer un nouveau compte	Create an account
		
se souvenir de moi	remember me
Mot de passe oublié	Forgot your password
Ou entrez ici une référence	Or enter a reference here


Utilisateur inconnu	Unknown user
Se deconnecter	Logout
mon profil	my profile
mot de passe	password



Vous n'avez pas remplis tous les champs obligatoires	You didn't fill all required fields		

Mot de passe	Password	
Confirmation de l'email	Confirm email
Confirmation du mot de passe	Confirm password
Salutation	Title
Langue	Language
Nom	Lastname
Prénom	Firstname
Téléphone	Phone	
Rue	Street
Numéro	Number	
Code postal	ZIP code
Ville	City	
Pays	Country
Fax	
Enregistrer	Save
champs obligatoires	required fields

L'adresse email de confirmation de correspond pas	Emails don't match
Le mot de passe de confirmation de correspond pas	Passwords don't match
Pour confirmer votre inscription, veuillez cliquer sur ce lien	To confirm registration, please click here

Votre demande a bien été enregistrée.<br/> Vous allez recevoir un email de confirmation à l'adresse	Your request has been recorded.<br/>You will receive a confirmation email to

Pour vous enregistrer veuillez utiliser le formulaire ci-après	To register, please fill the form bellow
Merci	Thank you