caravane_estate_frontend_api_login:
    path:     /api/login_check
    defaults: { _controller: "CaravaneEstateBundle:Api:login", _format: json }



caravane_estate_frontend_api_estate_search_sale:
    path:     /api/estate/search/{type}
    defaults: { _controller: "CaravaneEstateBundle:Api:search", _format: json }



caravane_estate_frontend_api_estate_pict_show:
    path:     /api/estate/pict/{filter}/{relativePath}
    defaults: { _controller: "CaravaneEstateBundle:Api:getPict" }
    requirements:
        relativePath: ".+"

