caravane_estate_frontend_api_login:
    path:     /api/login_check
    defaults: { _controller: "CaravaneEstateBundle:Api:login", _format: json }

caravane_estate_frontend_api_recover:
    path:     /api/recover
    defaults: { _controller: "CaravaneEstateBundle:Api:recover", _format: json }

caravane_estate_frontend_api_register:
    path:     /api/register
    defaults: { _controller: "CaravaneEstateBundle:Api:register", _format: json }

caravane_estate_frontend_api_facebook:
    path:     /api/facebook
    defaults: { _controller: "CaravaneEstateBundle:Api:facebook", _format: json }


caravane_estate_frontend_api_user:
    path:     /api/user
    defaults: { _controller: "CaravaneEstateBundle:Api:getUser", _format: json }


caravane_estate_frontend_api_home:
    path:     /api/home
    defaults: { _controller: "CaravaneEstateBundle:Api:getHome", _format: json  }

caravane_estate_push:
    path:     /notification/push
    defaults: { _controller: "CaravaneEstateBundle:Push:push"  }

caravane_estate_frontend_api_estate_pict_show:
    path:     /api/estate/pict/{filter}/{relativePath}
    defaults: { _controller: "CaravaneEstateBundle:Api:getPict" }
    requirements:
        relativePath: ".+"


caravane_estate_frontend_api_estate_search_sale:
    path:     /api/user/estate/search/{type}
    defaults: { _controller: "CaravaneEstateBundle:Api:search", _format: json }

caravane_estate_frontend_api_estate_search_around:
    path:     /api/user/estate/searcharound
    defaults: { _controller: "CaravaneEstateBundle:Api:searchAround", _format: json }


caravane_estate_frontend_api_user_update:
    path:     /api/user/update
    defaults: { _controller: "CaravaneEstateBundle:Api:updateUser", _format: json }


