caravane_estate_backend:
    path:     /admin
    defaults: { _controller: "CaravaneEstateBundle:Estate:adminSearch" }

caravane_estate_backend_estate:
    path:     /admin/estate
    defaults: { _controller: "CaravaneEstateBundle:Estate:index" }

caravane_estate_backend_estate_import:
    path:     /admin/estate/import
    defaults: { _controller: "CaravaneEstateBundle:Estate:import" }

caravane_estate_backend_estate_export:
    path:     /admin/estate/export
    defaults: { _controller: "CaravaneEstateBundle:Estate:export" }

caravane_estate_backend_estate_show:
    path:     /admin/estate/{id}/show
    defaults: { _controller: "CaravaneEstateBundle:Estate:show" }

caravane_estate_backend_estate_new:
    path:     /admin/estate/new
    defaults: { _controller: "CaravaneEstateBundle:Estate:new" }

caravane_estate_backend_estate_create:
    path:     /admin/estate/create
    defaults: { _controller: "CaravaneEstateBundle:Estate:create" }
    requirements: { _method: post }

caravane_estate_backend_estate_edit:
    path:     /admin/estate/{id}/edit
    defaults: { _controller: "CaravaneEstateBundle:Estate:edit" }

caravane_estate_backend_estate_update:
    path:     /admin/estate/{id}/update
    defaults: { _controller: "CaravaneEstateBundle:Estate:update" }
    requirements: { _method: post|put }

caravane_estate_backend_estate_delete:
    path:     /admin/estate/{id}/delete
    defaults: { _controller: "CaravaneEstateBundle:Estate:delete" }
    requirements: { _method: post|delete }



caravane_estate_frontend_estate_last_updated:
    path:     /estate/last
    defaults: { _controller: "CaravaneEstateBundle:Estate:lastUdated" }


caravane_estate_frontend_estate_search:
    path:     /estate/search
    defaults: { _controller: "CaravaneEstateBundle:Estate:search" }


caravane_estate_frontend_estate_search_sale:
    path:     /estate/search/sale
    defaults: { _controller: "CaravaneEstateBundle:Estate:search" }

caravane_estate_frontend_estate_search_rent:
    path:     /estate/search/rent
    defaults: { _controller: "CaravaneEstateBundle:Estate:search" }

caravane_estate_frontend_estate_search_new:
    path:     /estate/search/new
    defaults: { _controller: "CaravaneEstateBundle:Estate:search" }



caravane_estate_frontend_estate_search_from:
    path:     /estate/searchForm/{type}
    defaults: { _controller: "CaravaneEstateBundle:Estate:searchForm" }
    options:
        expose: true

caravane_estate_frontend_estate_search_by_area:
    path:     /estate/search/area/{type}/{id}
    defaults: { _controller: "CaravaneEstateBundle:Estate:searchByArea" }
    options:
        expose: true

caravane_estate_frontend_estate_search_count_by_area:
    path:     /estate/search/count/{type}
    defaults: { _controller: "CaravaneEstateBundle:Estate:searchByAreas" }
    options:
        expose: true

caravane_estate_frontend_estate_print:
    path:   /print/{reference}
    defaults: { _controller: "CaravaneEstateBundle:Estate:print" }

caravane_estate_frontend_estate_new_list:
    path:   /vente/bien-neuf
    defaults: { _controller: "CaravaneEstateBundle:Estate:newList" }

caravane_estate_frontend_estate_sale_show:
    path:   /vente/{reference}
    defaults: { _controller: "CaravaneEstateBundle:Estate:saleView" }

caravane_estate_frontend_estate_rent_show:
    path:   /location/{reference}
    defaults: { _controller: "CaravaneEstateBundle:Estate:rentView" }

caravane_estate_frontend_estate_sale_show:
    path:   /sale/{reference}
    defaults: { _controller: "CaravaneEstateBundle:Estate:saleView" }

caravane_estate_frontend_estate_rent_show:
    path:   /rent/{reference}
    defaults: { _controller: "CaravaneEstateBundle:Estate:rentView" }

caravane_estate_frontend_estate_sale_list:
    path:   /vente
    defaults: { _controller: "CaravaneEstateBundle:Estate:saleList" }

caravane_estate_frontend_estate_rent_list:
    path:   /location
    defaults: { _controller: "CaravaneEstateBundle:Estate:rentList" }

caravane_estate_frontend_estate_sale_list:
    path:   /sale
    defaults: { _controller: "CaravaneEstateBundle:Estate:saleList" }

caravane_estate_frontend_estate_rent_list:
    path:   /rent
    defaults: { _controller: "CaravaneEstateBundle:Estate:rentList" }





caravane_estate_frontend_estate_detail:
    path:   /estate/detail/{id}
    defaults: { _controller: "CaravaneEstateBundle:Estate:detail" }

caravane_estate_frontend_estate_rows:
    path:   /estate/rows
    defaults: { _controller: "CaravaneEstateBundle:Estate:rows" }


caravane_estate_frontend_estate_add_to_favorite:
    path: /estate/{id}/favorite
    defaults: { _controller: "CaravaneEstateBundle:Estate:addToFavorite" }
    options:
        expose: true
