caravane_estate_backend_estate:
    path:     /_admin/estate
    defaults: { _controller: "CaravaneEstateBundle:Estate:index" }

caravane_estate_backend_estate_show:
    path:     /_admin/estate/{id}/show
    defaults: { _controller: "CaravaneEstateBundle:Estate:show" }

caravane_estate_backend_estate_new:
    path:     /_admin/estate/new
    defaults: { _controller: "CaravaneEstateBundle:Estate:new" }

caravane_estate_backend_estate_create:
    path:     /_admin/estate/create
    defaults: { _controller: "CaravaneEstateBundle:Estate:create" }
    requirements: { _method: post }

caravane_estate_backend_estate_edit:
    path:     /_admin/estate/{id}/edit
    defaults: { _controller: "CaravaneEstateBundle:Estate:edit" }

caravane_estate_backend_estate_update:
    path:     /_admin/estate/{id}/update
    defaults: { _controller: "CaravaneEstateBundle:Estate:update" }
    requirements: { _method: post|put }

caravane_estate_backend_estate_delete:
    path:     /_admin/estate/{id}/delete
    defaults: { _controller: "CaravaneEstateBundle:Estate:delete" }
    requirements: { _method: post|delete }



caravane_estate_frontend_estate_last_updated:
    path:     /estate/last
    defaults: { _controller: "CaravaneEstateBundle:Estate:lastUdated" }


caravane_estate_frontend_estate_search:
    path:     /estate/search
    defaults: { _controller: "CaravaneEstateBundle:Estate:search" }



caravane_estate_frontend_estate_search_from:
    path:     /estate/searchForm
    defaults: { _controller: "CaravaneEstateBundle:Estate:searchForm" }



caravane_estate_frontend_estate_sale_show:
    path:   /vente/030/{reference}
    defaults: { _controller: "CaravaneEstateBundle:Estate:saleView" }

caravane_estate_frontend_estate_rent_show:
    path:   /location/030/{reference}
    defaults: { _controller: "CaravaneEstateBundle:Estate:rentView" }

caravane_estate_frontend_estate_sale_list:
    path:   /vente
    defaults: { _controller: "CaravaneEstateBundle:Estate:saleList" }

caravane_estate_frontend_estate_rent_list:
    path:   /location
    defaults: { _controller: "CaravaneEstateBundle:Estate:rentList" }

caravane_estate_frontend_estate_detail:
    path:   /estate/detail/{id}
    defaults: { _controller: "CaravaneEstateBundle:Estate:detail" }

caravane_estate_frontend_estate_rows:
    path:   /estate/rows
    defaults: { _controller: "CaravaneEstateBundle:Estate:rows" }