Banners:
    type: entity
    table: banners
    uniqueConstraints:
        ranking:
            columns:
                - ranking
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        photo:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        ranking:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
