Estate:
    type: entity
    table: Estate
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        datein:
            type: date
            nullable: true
            comment: ''
        updatedate:
            type: date
            nullable: false
            comment: ''
            column: updateDate
        photo:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        prix:
            type: decimal
            nullable: true
            precision: 8
            scale: 0
            comment: ''
        oldprix:
            type: decimal
            nullable: false
            precision: 8
            scale: 0
            comment: ''
            column: oldPrix
        locfr:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        locuk:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        areaId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: area_id
        zone:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        shortdescrfr:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        shortdescren:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        descrfr:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        descren:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        vendu:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
        surdemande:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
        actif:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
        location:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
        reference:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        enoption:
            type: string
            nullable: true
            length: 1
            fixed: true
            comment: ''
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        type:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        zip:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        googleMap:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: google_map
        moredescrfr:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        area:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        rooms:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        bathrooms:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        garages:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        garden:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
        viewable:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
        public:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: checked
        photobck:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        tphoto:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
            default: ''
        dayview:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        weekview:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        monthview:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        totalview:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        lastdayview:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        lastweekview:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        lastmonthview:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        lat:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: Lat
        lng:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: Lng
        processed:
            type: boolean
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
