Location:
    type: entity
    table: Location
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        zip:
            type: string
            nullable: false
            length: 4
            fixed: false
            comment: ''
            default: ''
        fr:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        nl:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        innercity:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: 'true'
        fixed:
            type: string
            nullable: false
            length: 5
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
