Photo:
    type: entity
    table: Photo
    uniqueConstraints:
        item_id:
            columns:
                - estate_id
                - photo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estateId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: estate_id
        photo:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        ranking:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
