Search:
    type: entity
    table: Search
    uniqueConstraints:
        userId:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
            column: user_id
        type:
            type: string
            nullable: false
            length: 3
            fixed: true
            comment: ''
            default: ''
        price:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        location:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        searchfor:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        mobilePossessiontypes:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: mobile_possessiontypes
        mobileZipcodes:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: mobile_zipcodes
    lifecycleCallbacks: {  }
