Slideshow:
    type: entity
    table: slideshow
    uniqueConstraints:
        ranking:
            columns:
                - ranking
        item_id:
            columns:
                - item_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        itemId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: item_id
        ranking:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
