UserEstate:
    type: entity
    table: user_estate
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
            column: user_id
        estateId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
            column: estate_id
        date:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        counter:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        saved:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        view:
            type: boolean
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
