User:
    type: entity
    table: User
    uniqueConstraints:
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        password:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        ip:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        session:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        cookie:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        admin:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        language:
            type: string
            nullable: false
            length: 2
            fixed: true
            comment: ''
            default: ''
        firstname:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        lastname:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        tel:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        zip:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
        fax:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        street:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        number:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
        city:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        country:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        company:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
        salutation:
            type: string
            nullable: false
            length: 3
            fixed: true
            comment: ''
            default: ''
        date:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
        lastvisit:
            type: datetime
            nullable: false
            comment: ''
            column: lastVisit
        status:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: pending
    lifecycleCallbacks: {  }
