ZipEstate:
    type: entity
    table: zip_estate
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        locationzip:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: '0'
            column: locationZip
        estateId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: estate_id
    lifecycleCallbacks: {  }
