MobileUdids:
    type: entity
    table: mobile_udids
    uniqueConstraints:
        udid:
            columns:
                - udid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: user_id
        udid:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        device:
            type: string
            nullable: false
            length: 7
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
