Stat:
    type: entity
    table: Stat
    uniqueConstraints:
        type:
            columns:
                - type
                - date
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
        date:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
