caravane_estate_slideshow:
    resource: "@CaravaneEstateBundle/Resources/config/routing/slideshow.yml"
    prefix:   /

caravane_estate_admin_estate:
    resource: "@CaravaneEstateBundle/Resources/config/routing/estate.yml"
    prefix:   /

caravane_estate_api_estate:
    resource: "@CaravaneEstateBundle/Resources/config/routing/api.yml"
    prefix:   /



install:
    path:     /install
    defaults: { _controller: "CaravaneEstateBundle:Default:install"}
#caravane_estate_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: CaravaneEstateBundle:Default:index }
