services:
    caravane_estate.form.type.search:
        class: Caravane\Bundle\EstateBundle\Form\SearchType
        tags:
            - { name: form.type, alias: search_form }

#    caravane_estate.listener.serialization_listener:
#        class: Caravane\Bundle\EstateBundle\Listener\SerializationListener
#        tags:
#            - { name: serializer.pre_serialize, event: serializer.pre_serialize, method: onPreSerialize }

    caravane_estate.manager:
        class: Caravane\Bundle\EstateBundle\Manager\EstateManager
        arguments: ["@doctrine.orm.entity_manager","@ivory_google_map.geocoder"]

    fix_authentication_header_listener:
        class: Caravane\Bundle\EstateBundle\Listener\AuthenticationHeaderListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }