<?php

namespace Caravane\Bundle\EstateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EstateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstateRepository extends EntityRepository
{

	public function findLastUpdated($limit=3) {
		return $this->findBy(
			array(),
			array('updatedOn'=>'desc'),
			$limit
		);
	}



}
