<?php

namespace Caravane\Bundle\EstateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends EntityRepository
{




	public function getPrices() {
		return array("sale"=>$this->getPriceRanges('sale'),"rent"=> $this->getPriceRanges('rent'));
	}


	private function getPriceRanges($type) {
		$prices=$this->findBy(array('type'=>$type),array("price"=>"asc"));
		$i=0;$tB=array();
		foreach($prices as $price) {
			$tB[$i]=$price;
			$i++;
		}
		$i=0;
		for($i=0;$i<count($tB);$i++) {
			$price=$tB[$i];
			
			if($i==0) {
				$key=$type."_".$price->getId()."_-";
				$label=" - de ".$price->getPrice()." €";
			}
			else {
				$sPrice=$tB[$i-1];
				$key=$type."_".$sPrice->getId()."_".$price->getId();
				$label="de ".$sPrice->getPrice()." à ".$price->getPrice()." €";
			}
			$tA[$key]=$label;
		}
		$price=$tB[count($prices)-1];
		$key=$type."_".$price->getId()."_+";
		$label=" + de ".$price->getPrice()." €";
		$tA[$key]=$label;
		return $tA;
	}
}
